# Generated by Django 4.2.6 on 2024-11-23 23:25

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeLeave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_balance', models.IntegerField(default=15)),
                ('total_delay', models.DurationField(default=datetime.timedelta)),
                ('annual_leave', models.IntegerField(default=15)),
                ('remaining_leave', models.IntegerField(default=0)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='management.employee')),
            ],
        ),
        migrations.CreateModel(
            name='WorkHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('clock_in', models.DateTimeField()),
                ('clock_out', models.DateTimeField()),
                ('delay', models.DurationField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.employee')),
            ],
        ),
        migrations.DeleteModel(
            name='AttendanceRecord',
        ),
    ]
