# Generated by Django 4.2.6 on 2024-11-24 14:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('management', '0004_rename_employeeleave_employeeleaveinfo_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagerDashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_employees', models.IntegerField(default=0)),
                ('total_leave_requests', models.IntegerField(default=0)),
                ('total_approved_leaves', models.IntegerField(default=0)),
                ('total_rejected_leaves', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeDashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_work_hours', models.DurationField(default=0)),
                ('remaining_leave_days', models.IntegerField(default=0)),
                ('total_leave_days_taken', models.IntegerField(default=0)),
                ('total_late_days', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
